#User Types:   0 - anonymous, 1 - Customer, 2 - Employee, 3 - Manager, 4 - Superadmin
auth:
#Signin
      - path: /viiva/auth/signin
        method: POST
        roles: [0]
#Signup
      - path: /viiva/auth/signup
        method: POST
        roles: [0]
#Logout
      - path: /viiva/auth/logout
        method: POST
        roles: [1,2,3,4]
#View All Users
      - path: /viiva/user
        method: GET
        roles: [2,3,4]
#View User Details
      - path: /viiva/user/:id
        method: GET
        roles: [1,2,3,4]
#Update User Details
      - path: /viiva/user/:id
        method: PUT
        roles: [1,2,3,4]
#Delete User Details
      - path: /viiva/user/:id
        method: DELETE
        roles: [3,4]
#View All Accounts
      - path: /viiva/account
        method: GET
        roles: [2,3,4]
#View Account Details (All Accounts)
      - path: /viiva/user/:id/accounts
        method: GET
        roles: [1,2,3,4]
#View Account Detail (Individual Account)
      - path: /viiva/account/:id
        method: GET
        roles: [1,2,3,4]
#Update User Pin
      - path: /viiva/account/:id
        method: PUT
        roles: [1,2,3,4]
#View All the transactions
      - path: /viiva/transactions
        method: GET
        roles: [2,3,4]
#View Transactions (All Accounts)
      - path: /viiva/user/:id/transactions
        method: GET
        roles: [1,2,3,4]
#View Transactions (Individual Account)
      - path: /viiva/account/:id/transactions
        method: GET
        roles: [1,2,3,4]
#Make Payments
      - path: /viiva/transactions
        method: POST
        roles: [1,2,3,4]
#Request a New Account
      - path: /viiva/account
        method: POST
        roles: [1,2,3,4]
#Delete Existing Account
      - path: /viiva/account/:id
        method: DELETE
        roles: [3,4]
#View Branch Info
      - path: /viiva/branch/:id
        method: GET
        roles: [1,2,3,4]
#View All Branches
      - path: /viiva/branch
        method: GET
        roles: [1,2,3,4]
#Add Branch Info
      - path: /viiva/branch
        method: POST
        roles: [4]
#Update Branch Info
      - path: /viiva/branch/:id
        method: PUT
        roles: [3,4]
#Delete Branch Info
      - path: /viiva/branch/:id
        method: DELETE
        roles: [4]
#View All Requests
      - path: /viiva/request
        method: GET
        roles: [2,3,4]
#View User Requests
      - path: /viiva/request/:id
        method: GET
        roles: [2,3,4]
#Approve User Requests
      - path: /viiva/request/:id
        method: PUT
        roles: [2,3,4]
#View All Employee
      - path: /viiva/employee
        method: GET
        roles: [2,3,4]
#View Employee
      - path: /viiva/employee/:id
        method: GET
        roles: [2,3,4]
#Add Employee
      - path: /viiva/employee
        method: POST
        roles: [3,4]
#Update Employee
      - path: /viiva/employee/:id
        method: PUT
        roles: [3,4]
#Delete Employee:
      - path: /viiva/employee/:id
        method: DELETE
        roles: [4]