routes:
    #Signin 
    - path: /viiva/auth/signin
      method: POST
      handler: com.viiva.handler.signin.SigninHandler

    #Signup done
    - path: /viiva/auth/signup
      method: POST
      handler: com.viiva.handler.signup.SignupHandler

    #Logout
    - path: /viiva/auth/logout
      method: POST
      handler: com.viiva.handler.session.SessionHandler

    #Add new User
    - path: /viiva/user
      method: POST
      handler: com.viiva.handler.user.UserHandler

    #View all users
    - path: /viiva/user
      method: GET
      handler: com.viiva.handler.user.UserHandler

    #View User Details  
    - path: /viiva/user/:id
      method: GET
      handler: com.viiva.handler.user.UserHandler	  

    #Update User Details
    - path: /viiva/user/:id
      method: PUT
      handler: com.viiva.handler.user.UserHandler
    
    #Delete User Details
    - path: /viiva/user/:id
      method: DELETE
      handler: com.viiva.handler.user.UserHandler

    #View All Accounts
    - path: /viiva/account
      method: GET
      handler: com.viiva.handler.account.AccountHandler

    #View Account Details (All Accounts)
    - path: /viiva/user/:id/accounts
      method: GET
      handler: com.viiva.handler.account.AccountHandler

    #View Account Detail (Individual Account)
    - path: /viiva/account/:id
      method: GET
      handler: com.viiva.handler.account.AccountHandler

    #Update Account Detail
    - path: /viiva/account/:id
      method: PUT
      handler: com.viiva.handler.account.AccountHandler

    #View All Transactions
    - path: /viiva/transactions
      method: GET
      handler: com.viiva.handler.transaction.TransactionHandler

    #View Transactions (All Accounts)
    - path: /viiva/user/:id/transactions
      method: GET
      handler: com.viiva.handler.transaction.TransactionHandler

    #View Transactions (Individual Account)
    - path: /viiva/account/:id/transactions
      method: GET
      handler: com.viiva.handler.transaction.TransactionHandler

    #Make Payments
    - path: /viiva/transactions
      method: POST
      handler: com.viiva.handler.transaction.TransactionHandler

    #Request a New Account
    - path: /viiva/account
      method: POST
      handler: com.viiva.handler.account.AccountHandler

    #Delete Existing Account
    - path: /viiva/account/:id
      method: DELETE
      handler: com.viiva.handler.account.AccountHandler

    #View All Branches
    - path: /viiva/branch
      method: GET
      handler: com.viiva.handler.branch.BranchHandler

    #View Branch Info
    - path: /viiva/branch/:id
      method: GET
      handler: com.viiva.handler.branch.BranchHandler

    #Add Branch Info
    - path: /viiva/branch
      method: POST
      handler: com.viiva.handler.branch.BranchHandler

    #Update Branch Info
    - path: /viiva/branch/:id
      method: PUT
      handler: com.viiva.handler.branch.BranchHandler
 
    #Delete Branch Info
    - path: /viiva/branch/:id
      method: DELETE
      handler: com.viiva.handler.branch.BranchHandler

    #View All Requests
    - path: /viiva/request
      method: GET
      handler: com.viiva.handler.request.RequestHandler

    #View User Requests
    - path: /viiva/request/:id
      method: GET
      handler: com.viiva.handler.request.RequestHandler

    #Approve User Requests
    - path: /viiva/request/:id
      method: PUT
      handler: com.viiva.handler.request.RequestHandler

    #View All employees
    - path: /viiva/employee
      method: GET
      handler: com.viiva.handler.employee.EmployeeHandler

    #View Employee
    - path: /viiva/employee/:id
      method: GET
      handler: com.viiva.handler.employee.EmployeeHandler

    #Add Employee
    - path: /viiva/employee
      method: POST
      handler: com.viiva.handler.employee.EmployeeHandler

    #Update Employee
    - path: /viiva/employee/:id
      method: PUT
      handler: com.viiva.handler.employee.EmployeeHandler

    #Delete Employee
    - path: /viiva/employee/:id
      method: DELETE
      handler: com.viiva.handler.employee.EmployeeHandler